site_name: civic-data-boundaries-us-forests Documentation
site_description: Documentation for civic-data-boundaries-us-forests
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
  features:
  - navigation.expand
nav:
- Home: index.md
- API Reference:
  - Developer: api/DEVELOPER.md
  - Readme: api/README.md
plugins:
- search
markdown_extensions:
- toc
- codehilite
- admonition
