site_name: civic-data-boundaries-us-forests Documentation
site_description: Documentation for civic-data-boundaries-us-forests
docs_dir: mkdocs_src
site_dir: docs
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
  features:
  - navigation.expand
nav:
- Home: index.md
- API Reference:
  - Chunk: api/chunk.md
  - Cleanup: api/cleanup.md
  - Cli.Cli: api/cli.cli.md
  - Export: api/export.md
  - Fetch: api/fetch.md
  - Index: api/index.md
  - Utils.Chunk Utils: api/utils.chunk_utils.md
  - Utils.Export Utils: api/utils.export_utils.md
  - Utils.Get Paths: api/utils.get_paths.md
plugins:
- search
markdown_extensions:
- toc
- codehilite
- admonition
