site_name: civic-data-boundaries-us-forests Documentation
site_description: Documentation for civic-data-boundaries-us-forests
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
  features:
  - navigation.expand
nav:
- Home: index.md
- API Reference:
    - civic_data_boundaries_us_forests.chunk: api/civic_data_boundaries_us_forests.chunk.md
    - civic_data_boundaries_us_forests.cleanup: api/civic_data_boundaries_us_forests.cleanup.md
    - civic_data_boundaries_us_forests.cli.cli: api/civic_data_boundaries_us_forests.cli.cli.md
    - civic_data_boundaries_us_forests.export: api/civic_data_boundaries_us_forests.export.md
    - civic_data_boundaries_us_forests.fetch: api/civic_data_boundaries_us_forests.fetch.md
    - civic_data_boundaries_us_forests.index: api/civic_data_boundaries_us_forests.index.md
    - civic_data_boundaries_us_forests.utils.chunk_utils: api/civic_data_boundaries_us_forests.utils.chunk_utils.md
    - civic_data_boundaries_us_forests.utils.export_utils: api/civic_data_boundaries_us_forests.utils.export_utils.md
    - civic_data_boundaries_us_forests.utils.get_paths: api/civic_data_boundaries_us_forests.utils.get_paths.md

plugins:
- search
markdown_extensions:
- toc
- codehilite
- admonition
